defaults:
  - base
  - _self_

model:
  vocab_size: ${data.vocab_size}
  embedding_dim: 20
  hidden_dim: 130
  n_layers: 3
  seq_len: ${data.max_seq_len}
  learning_rate: ${general.learning_rate}
  max_epochs: ${general.max_epochs}

data:
  vocab_size: 10_000
  max_seq_len: 400

general:
  max_epochs: 10
  batch_size: 300
  learning_rate: 0.005